# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."factorio" = {
    image = "factoriotools/factorio";
    environment = {
      "DLC_SPACE_AGE" = "false";
    };
    volumes = [
      "/var/lib/factorio:/factorio:rw"
    ];
    ports = [
      "34197:34197/udp"
      "27015:27015/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=factorio"
      "--network=factorio_default"
    ];
  };
  systemd.services."podman-factorio" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-factorio_default.service"
    ];
    requires = [
      "podman-network-factorio_default.service"
    ];
    partOf = [
      "podman-compose-factorio-root.target"
    ];
    wantedBy = [
      "podman-compose-factorio-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-factorio_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f factorio_default";
    };
    script = ''
      podman network inspect factorio_default || podman network create factorio_default
    '';
    partOf = [ "podman-compose-factorio-root.target" ];
    wantedBy = [ "podman-compose-factorio-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-factorio-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
