# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."govee2mqtt" = {
    image = "ghcr.io/wez/govee2mqtt:latest";
    environment = {
      "GOVEE_EMAIL" = "drewkrause2@gmail.com";
      "GOVEE_MQTT_HOST" = "localhost";
      "GOVEE_MQTT_PORT" = "1883";
      "GOVEE_TEMPERATURE_SCALE" = "F";
      "RUST_LOG_STYLE" = "always";
      "TZ" = "America/Chicago";
    };
    environmentFiles = [ config.sops.secrets.govee_env.path ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-govee2mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-home-assistant-root.target"
    ];
    wantedBy = [
      "podman-compose-home-assistant-root.target"
    ];
  };
  virtualisation.oci-containers.containers."home-assistant-eclipse-mosquitto" = {
    image = "eclipse-mosquitto";
    ports = [
      "1883:1883/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=eclipse-mosquitto"
      "--network=home-assistant_default"
    ];
  };
  systemd.services."podman-home-assistant-eclipse-mosquitto" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-home-assistant_default.service"
    ];
    requires = [
      "podman-network-home-assistant_default.service"
    ];
    partOf = [
      "podman-compose-home-assistant-root.target"
    ];
    wantedBy = [
      "podman-compose-home-assistant-root.target"
    ];
  };
  virtualisation.oci-containers.containers."homeassistant" = {
    image = "ghcr.io/home-assistant/home-assistant:stable";
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/var/lib/HomeAssistant:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-homeassistant" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-home-assistant-root.target"
    ];
    wantedBy = [
      "podman-compose-home-assistant-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-home-assistant_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f home-assistant_default";
    };
    script = ''
      podman network inspect home-assistant_default || podman network create home-assistant_default
    '';
    partOf = [ "podman-compose-home-assistant-root.target" ];
    wantedBy = [ "podman-compose-home-assistant-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-home-assistant-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
