# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mc-server-bds" = {
    image = "itzg/minecraft-bedrock-server";
    environment = {
      "DIFFICULTY" = "hard";
      "EULA" = "TRUE";
      "LEVEL_NAME" = "§l§4C§fC§4U";
      "MAX_PLAYERS" = "100";
      "PLAYER_IDLE_TIMEOUT" = "0";
      "SERVER_NAME" = "§l§4C§fC§4U";
    };
    volumes = [
      "/var/lib/mc-server/data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-mc-server-bds" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-mc-server-root.target"
    ];
    wantedBy = [
      "podman-compose-mc-server-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mc-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
