# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tml" = {
    image = "localhost/compose2nix/tml";
    volumes = [
      "/var/lib/terraria-server/tModLoader:/home/tml/.local/share/Terraria/tModLoader:rw"
    ];
    ports = [
      "7777:7777/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tml"
      "--network=terraria-server_default"
    ];
  };
  systemd.services."podman-tml" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-terraria-server_default.service"
    ];
    requires = [
      "podman-network-terraria-server_default.service"
    ];
    partOf = [
      "podman-compose-terraria-server-root.target"
    ];
    wantedBy = [
      "podman-compose-terraria-server-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-terraria-server_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f terraria-server_default";
    };
    script = ''
      podman network inspect terraria-server_default || podman network create terraria-server_default
    '';
    partOf = [ "podman-compose-terraria-server-root.target" ];
    wantedBy = [ "podman-compose-terraria-server-root.target" ];
  };

  # Builds
  systemd.services."podman-build-tml" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/drew/containers/terraria-server
      podman build -t compose2nix/tml --build-arg GID=1000 --build-arg UID=1000 .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-terraria-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
