# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environment = {
      "ROCKET_PORT" = "6574";
      "WEBSOCKET_ENABLED" = "\"true\"";
    };
    volumes = [
      "/var/lib/vaultwarden/vw-data:/data:rw"
    ];
    ports = [
      "6574:6574/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_default"
    ];
  };
  systemd.services."podman-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vaultwarden_default.service"
    ];
    requires = [
      "podman-network-vaultwarden_default.service"
    ];
    partOf = [
      "podman-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "podman-compose-vaultwarden-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-vaultwarden_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f vaultwarden_default";
    };
    script = ''
      podman network inspect vaultwarden_default || podman network create vaultwarden_default
    '';
    partOf = [ "podman-compose-vaultwarden-root.target" ];
    wantedBy = [ "podman-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
